baseURL: 'https://ppphp.github.io/'
languageCode: 'zh-cn'
title: "a usr/bin"

hasCJKLanguage: true

DisqusShortname: 'ppphp-1'

params:
  comments: true

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
