baseURL: 'https://ppphp.github.io/'
languageCode: 'zh-cn'
title: "a usr/bin"

buildDrafts: false
buildFuture: false
buildExpired: false
hasCJKLanguage: true

DisqusShortname: 'ppphp-1'

params:
  comments: true
  
  DateFormat: "2006-1-2"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
