baseURL = 'https://ppphp.github.io/'
languageCode = 'zh-cn'
title = "a usr/bin"

theme = "PaperMod"
# contentDir="org"
hasCJKLanguage=true

disqusShortname = 'ppphp-1.disqus.io'

[params]
comments= true