#+TITLE: blender基本使用
#+TAGS[]: graphics

介绍最基本的blender使用

反正都是辣椒酱教的

* 移动视角

- 旋转：中键
- 平移：Shift-中键
- 缩放：滚轮

右上角按住柄旋转，按住线平移

小键盘0控制进出摄像机视角

右边有个摄像机的按钮

小键盘5控制进出透视视图或正交视角

右边有个网格

锁定摄像机视角按n键然后点相机锁定模式，可以让摄像机跟随视角移动

C-M-小键盘0 可以让摄像机瞬间飞到当前视角

C-M-q可以进出四视图

小键盘7是顶视图，1是前视图，3是左视图

C-7 C-1 C-3 是对面的视图

小键盘9是观察视角翻转

小键盘.键快速聚焦选中物体，C-.可以在四视图中聚焦

小键盘/键可屏蔽没有选中的物体

小键盘home键可以聚焦整体场景。

* 操作物体

箭头平移，手柄缩放，圆环旋转

快捷键是g,s,r,加数字是数量，加xyz是轴

右上角有个icon，看上去像突破大气层，是gizmo的开关，C-~开启关闭gizmo

添加物品S-a

复制S-d

S-鼠标右键可以移动游标位置，游标模式也可以拖

原点可以右键设置回到几何中心

tab键进入编辑模式，按1是点，按2是边，按3是面

活动物体是最后选中的物体，选中物体是所有物体

C-j 合并选中物体，原点是活动物体

编辑模式下L选中相连物体

编辑模式下P分离物体，等于选中的创建新物体

C-~进入fps模式，wasd方向，qe上下，SM加速减速，空格跳到瞄准物体上

M-o 平滑关键帧

选中物体h键隐藏，M-h恢复，S-h批量隐藏

F12渲染

C-p把活动物体作为选中物体的父级，也可以在对象栏拖

C-m交互镜像，可以中键拖


* 坐标
坐标系在界面正上方，一开始是全局，可以选局部，法向，万向，视图，游标

按xyz之后，重复xyz切换局部和全局的坐标系

,号也可以复制坐标系，可以甩

轴心点在坐标系右边，初始都是质心，图标像一个锁，批量操作物体的时候设置缩放中心，旋转中心这种

* 吸附

吸附图标在轴心点右边，图标像磁铁

操作(gsr)的时候按ctrl可以切换吸附状态

右边的图标设置吸附的模式

增量是吸附到背景网格，就是整数移动的意思

点边面，边中点这种吸附比较多

* 衰减

衰减是批量编辑的工具，按钮在吸附模式的右边，图标是两个圈。

衰减的圈里的对象会在选中对象操作时也改变状态，就是会根据模式改多改少。

右边是衰减模式，可以选。

* 游标

S-右键改变游标位置

S-s游标相关甩饼操作，可以移动物体或者移动游标
